# Generated by Django 5.2.4 on 2025-08-01 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_title', models.CharField(help_text='Title of the bug', max_length=200)),
                ('bug_description', models.TextField(help_text='Detailed description of the bug')),
                ('bug_status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', help_text='Current status of the bug', max_length=20)),
                ('bug_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level of the bug', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_user', models.ForeignKey(blank=True, help_text='User assigned to fix this bug', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bugs', to=settings.AUTH_USER_MODEL)),
                ('created_by_user', models.ForeignKey(help_text='User who reported this bug', on_delete=django.db.models.deletion.CASCADE, related_name='created_bugs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bug',
                'verbose_name_plural': 'Bugs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_message', models.TextField(help_text='Content of the comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commenter_user', models.ForeignKey(help_text='User who made this comment', on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
                ('related_bug', models.ForeignKey(help_text='Bug this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='bug_comments', to='tracker.bug')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Name of the project', max_length=200)),
                ('project_description', models.TextField(help_text='Detailed description of the project')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_owner', models.ForeignKey(help_text='User who owns this project', on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bug',
            name='related_project',
            field=models.ForeignKey(help_text='Project this bug belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='project_bugs', to='tracker.project'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('bug_created', 'Bug Created'), ('bug_updated', 'Bug Updated'), ('bug_status_changed', 'Bug Status Changed'), ('comment_added', 'Comment Added'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated')], max_length=20)),
                ('activity_description', models.TextField(help_text='Description of the activity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_user', models.ForeignKey(help_text='User who performed this activity', on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to=settings.AUTH_USER_MODEL)),
                ('related_bug', models.ForeignKey(blank=True, help_text='Bug related to this activity (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug_activities', to='tracker.bug')),
                ('related_project', models.ForeignKey(help_text='Project related to this activity', on_delete=django.db.models.deletion.CASCADE, related_name='project_activities', to='tracker.project')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
